# Generated by Django 4.2.20 on 2025-05-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
