# Generated by Django 4.2.20 on 2025-05-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_date_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
