# Generated by Django 4.2.20 on 2025-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_date_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='protein',
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.DateField(),
        ),
    ]
