# Generated by Django 4.2.20 on 2025-05-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='date',
        ),
        migrations.RemoveField(
            model_name='food',
            name='meal',
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='grams',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
